### ISSUE TITLE
ElysiaJS link points to a wrong project

### ISSUE THREAD

**Issue by latenightdef** [creatorsgarten/open.source.in.th#6]
Currently the Elysia link points to https://www.github.com/elysia/elysia which is not a TypeScript framework as described on the page.

It should point to https://github.com/elysiajs/elysia instead.

**Comment by heypoom** [comment]
Great catch @latenightdef! I've updated the ring.json file krub.

PS. @suntiparb72, I saw your referenced commit krub - thank you! Feel free to count your commit as a PR contribution towards getting the shirt~
