### ISSUE TITLE
Can we add open source projects that is not mine?

### ISSUE THREAD

**Issue by pavaris-pm** [creatorsgarten/open.source.in.th#7]
Does it necessary to add just only my open source project ? or we can add any project that is open source in Thailand. since it has many interesting open source project in Thailand nowadays, and i think that it would be better if we can help them to promote their project as well.

**Comment by heypoom** [comment]
Hey @pavaris-pm! You can add any open source projects here if it helps krub. If you are not sure if the maintainer will be okay with it, you can ask for their consent first and add it here. Thanks!

**Comment by pavaris-pm** [comment]
Thank you 🙏🏻
